# To install the git pre-commit hook run:
#   pre-commit install
# To update the pre-commit hooks run:
#   pre-commit install-hooks
exclude: '^(\.tox|ci/templates|\.bumpversion\.cfg)(/|$)'
repos:
  - repo: local
    hooks:
      - id: export-solved-default-env
        name: export-solved-default-env
        entry: |-
          bash -c '
            pixi r --frozen micromamba env export > solved-env.yml \
            && git add --intent-to-add solved-env.yml              \
            && git diff --exit-code --no-patch solved-env.yml      \
          '
        language: system
        files: "pixi.lock"
        pass_filenames: false
      - id: export-solved-qubekit-env
        name: export-solved-qubekit-env
        entry: |-
          bash -c '
            pixi r -e qubekit --frozen micromamba env export > solved-qubekit-env.yml \
            && git add --intent-to-add solved-qubekit-env.yml                         \
            && git diff --exit-code --no-patch solved-qubekit-env.yml                 \
          '
        language: system
        files: "pixi.lock"
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: "solved-(.*-)?env.yml"
      - id: end-of-file-fixer
      - id: debug-statements
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.20.0
    hooks:
      - id: pyupgrade
        args:
          - --py311-plus
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.2.0
    hooks:
      - id: add-trailing-comma
        files: "workflow"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.10
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
        files: "workflow"
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        files: ^examples
