[project]
name = "back-to-school-josh"
authors = ["Josh Mitchell <josh.mitchell@openforcefield.org>"]
channels = ["conda-forge", "openeye"]
platforms = ["linux-64"]
license-file = "LICENSE"

[dependencies]
python = ">=3.11,<3.13"
smee = ">=0.16.2,<0.17"
descent = ">=0.5.2,<0.6"
typer-slim = ">=0.16.1,<0.17"
openff-toolkit = ">=0.17.0,<0.18"
openff-interchange = ">=0.4.5,<0.5"
rdkit = ">=2023.9.6,<2024"
openff-qcsubmit = ">=0.56.0,<0.57"
openeye-toolkits = ">=2025.1.1,<2026"
loguru = ">=0.7.3,<0.8"
tqdm = ">=4.67.1,<5"
datasets = ">=4.0.0,<5"
h5py = ">=3.13.0,<4"
numpy = ">=1.26.4,<2"
pandas = ">=2.1.4,<3"
matplotlib = ">=3.10.5,<4"

[pypi-dependencies]
back-to-school-josh = { path = "packages", editable = true }

[feature.qubekit.dependencies]
qubekit = ">=2.1.1,<3"
pydantic = ">=1.10.22,<2"
python = ">=3.11,<3.13"
openff-toolkit = ">=0.16.5,<0.17"
openff-qcsubmit = ">=0.56.0,<0.57"
typer-slim = ">=0.16.1,<0.17"
loguru = ">=0.7.3,<0.8"
tqdm = ">=4.67.1,<5"
numpy = ">=1.26.4,<2"
pandas = ">=2.1.4,<3"
setuptools = "<80"
cyclopts = ">=3.23.1,<4"

[feature.qubekit.pypi-dependencies]
back-to-school-josh = { path = "packages", editable = true }

[environments]
qubekit = { features = ["qubekit"], no-default-feature = true }

[tasks.create-step]
args = ["step_name"]
cmd = "mkdir workflow/{{ step_name }} && cp templates/__main__.py workflow/{{ step_name }}/__main__.py"
cwd = "."
