[project]
name = "back_to_school_josh"
version = "0.1.0"
description = "Add your description here"
authors = [
  { name = "Josh Mitchell", email = "yoshanuikabundi@gmail.com" },
]
requires-python = ">=3.11"
dependencies = []

[build-system]
requires = ["uv_build>=0.8.11,<0.9.0"]
build-backend = "uv_build"
